apiVersion: apps/v1
kind: Deployment
metadata:
  name: fs-app-1
  labels:
    app: fs-app-1
spec:
  replicas: 3
  selector:
    matchLabels:
      app: fs-app-1
  template:
    metadata:
      labels:
        app: fs-app-1
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
