apiVersion: v1
kind: Service
metadata:
  labels:
    app: freeswitch
  name: freeswitch-svc
  namespace: default
spec:
  type: ClusterIP
  clusterIP: None
  ports:
  - name: sip-udp
    port: 5060
    protocol: UDP
  - name: sip-tcp
    port: 5060
    protocol: TCP
  - name: esl-tcp
    port: 8021
    protocol: TCP
  selector:
    app: freeswitch
