apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: freeswitch
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: freeswitch
  serviceName: freeswitch-svc
  template:
    metadata:
      labels:
        app: freeswitch
    spec:
      containers:
      - name: freeswitch
        image: safarov/freeswitch
        ports:
        - containerPort: 5060
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
